# Generated by Django 4.1.6 on 2023-02-06 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
